#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor -d 1 2 3 4 5 6 7 8 9 0


bspc config border_width		1
bspc config window_gap			1
bspc config focused_border_color '#FFFFFF'

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a Floating state=floating
xdotool mousemove 9999 9999
xinput disable "$(xinput list --name-only | grep Touchpad)"
